<?xml version="1.0" encoding="utf-8" ?>
<Material>
  <RenderState>
    <BlendState>
      <Relative>opaque</Relative>
    </BlendState>
    <RasterizerState>
      <Relative>cullNone</Relative>
    </RasterizerState>
    <SamplerState>
      <Relative>linearWrap</Relative>
    </SamplerState>
    <DepthStencilState>
      <Relative>defaultdss</Relative>
    </DepthStencilState>
    <BlendFactor>
      <Color>
        <R>255</R>
        <G>255</G>
        <B>255</B>
        <A>255</A>
      </Color>
    </BlendFactor>
    <MultiSampleMask>-1</MultiSampleMask>
    <ReferenceStencil>0</ReferenceStencil>
  </RenderState>
  <Effect>
    <Relative>model</Relative>
  </Effect>
</Material>
